# Generated by Django 5.1.8 on 2025-05-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
